@startuml
curl --> libc6
curl --> libcurl4
curl --> zlib1g
libc6 --> libgcc-s1
libc6 --> libcrypt1
libc6 --> libidn2-0
libcurl4 --> libc6
libcurl4 --> libgnutls30
libcurl4 --> libssh-4
libcurl4 --> zlib1g
zlib1g --> libc6
@enduml
