@startuml
"accountsservice" --> "default-dbus-system-bus"
"accountsservice" --> "dbus-system-bus"
"accountsservice" --> "libaccountsservice0"
"accountsservice" --> "libc6"
"accountsservice" --> "libglib2.0-0t64"
"accountsservice" --> "libpolkit-gobject-1-0"
"libaccountsservice0" --> "libc6"
"libaccountsservice0" --> "libcrypt1"
"libaccountsservice0" --> "libglib2.0-0t64"
"libaccountsservice0" --> "libsystemd0"
"libc6" --> "libgcc-s1"
"libgcc-s1" --> "gcc-14-base"
"libgcc-s1" --> "libc6"
"libcrypt1" --> "libc6"
"libglib2.0-0t64" --> "libc6"
"libglib2.0-0t64" --> "libffi8"
"libglib2.0-0t64" --> "libmount1"
"libglib2.0-0t64" --> "libpcre2-8-0"
"libglib2.0-0t64" --> "libselinux1"
"libglib2.0-0t64" --> "zlib1g"
"libffi8" --> "libc6"
"libmount1" --> "libblkid1"
"libmount1" --> "libc6"
"libmount1" --> "libselinux1"
"libblkid1" --> "libc6"
"libselinux1" --> "libc6"
"libselinux1" --> "libpcre2-8-0"
"libpcre2-8-0" --> "libc6"
"zlib1g" --> "libc6"
"libsystemd0" --> "libc6"
"libsystemd0" --> "libcap2"
"libsystemd0" --> "libgcrypt20"
"libsystemd0" --> "liblz4-1"
"libsystemd0" --> "liblzma5"
"libsystemd0" --> "libzstd1"
"libcap2" --> "libc6"
"libgcrypt20" --> "libc6"
"libgcrypt20" --> "libgpg-error0"
"libgpg-error0" --> "libc6"
"liblz4-1" --> "libc6"
"liblzma5" --> "libc6"
"libzstd1" --> "libc6"
"libpolkit-gobject-1-0" --> "libc6"
"libpolkit-gobject-1-0" --> "libglib2.0-0t64"
"libpolkit-gobject-1-0" --> "libsystemd0"
@enduml
